FROM nginx:1.25.4-alpine

# Remoción de la configuración por defecto de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Inyección de la configuración institucional perimetral
COPY nginx.conf /etc/nginx/nginx.conf

# Copia de artefactos estáticos del sistema
COPY index.html /usr/share/nginx/html/index.html
COPY css/ /usr/share/nginx/html/css/
COPY src/ /usr/share/nginx/html/src/

# Configuración de permisos para ejecución segura sin privilegios de root
RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80

USER nginx

CMD ["nginx", "-g", "daemon off;"]