FROM nginx:1.25.4-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/ecosistema-frontend.conf

COPY ./src /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]