# frontend/docker-compose.yml
services:
  frontend-nginx:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    container_name: frontend_produccion
    ports:
      - "80:80" # Expone el sistema al mundo
    networks:
      - backend_net
    restart: unless-stopped

networks:
  backend_net:
    external: true