server {
    listen 80;
    server_name localhost;

    # Directorio raíz donde residen los archivos copiados en el Dockerfile
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Manejo de enrutamiento y fallback
        try_files $uri $uri/ /index.html;
    }

    # Optimización de almacenamiento en caché para assets estáticos
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # Manejo de errores globales
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}