services:
  api-bff:
    build: ./
    container_name: bff_orquestador
    env_file: 
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
      - MS_PERSONAS_URL=http://ms_personas_api:8000
      - MS_BIENES_URL=http://ms_bienes_api:8000
      - MS_RESGUARDOS_URL=http://ms_resguardos_api:8000
      - MS_UBICACIONES_URL=http://ms_ubicaciones_api:8000
      - MS_USUARIOS_URL=http://ms_usuarios_api:8000
    volumes:
      - ./:/app
    ports:
      - "${SERVER_IP}:${SERVER_PORT}:8000"
    networks:
      - backend_net
    restart: unless-stopped

networks:
  backend_net:
    external: true