services:
  api-ms-personas:
    build: ./
    container_name: ms_personas_api
    env_file: 
      - .env_code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - ${SERVER_IP}:${SERVER_PORT}:8000
    depends_on:
       db:
        condition: service_healthy
    networks:
        - backend_net
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: db_personas
    env_file: 
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - ./db-data-personas:/var/lib/postgresql/data
    networks:
        - backend_net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_personas
    ports:
      - ${PGADMIN_IP}:${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    volumes:
      - ./pgadmin-data-personas/:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy 
    networks:
        - backend_net 
    restart: unless-stopped

networks:
  backend_net:
    external: true